[package]
name = "platform-rs"
version = "0.1.0"
authors = ["funnydog <funnydog@users.noreply.github.com>"]

[dependencies]
glm = "0.2.0"
rand = "0.3"
time = ">=0.1"

[dependencies.sdl2]
version = "0.27"
default-features = false
features = ["ttf", "image"]